### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/browserbadge#25]
In order to pass this test you must create a sitemap.xml file for your website. Some of the best practices are listed below:
it is strongly recommended that you place your sitemap at the root directory of your website: http://yourwebsite.com/sitemap.xmlBut in some situations, you may want to produce different sitemaps for different paths on your site (e.g., security permission issues)
sitemaps should be no larger than 10MB (10,485,760 bytes) and can contain a maximum of 50,000 URLs. This means that if your site contains more than 50,000 URLs or your sitemap is bigger than 10MB, you must create multiple sitemap files and use a Sitemap index file
all URLs listed in the sitemap must reside on the same host as the sitemap. For instance, if the sitemap is located at http://www.yourwebsite.com/sitemap.xml, it can't include URLs from http://subdomain.yourwebsite.com
once you have created your sitemap, let search engines know about it by submitting directly to them, pinging them, or adding the sitemap location to your robots.txt file
sitemaps can be compressed using gzip, reducing bandwidth consumption
sitemap.xml example:
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
 <loc>http://www.yourwebsite.com</loc>
 <lastmod>2013-01-01</lastmod>
 <changefreq>weekly</changefreq>
 <priority>0.9</priority>
</url>
<url>
 <loc>http://www.yourwebsite.com/articles/100</loc>
 <changefreq>weekly</changefreq>
</url>
<url>
 <loc>http://www.yourwebsite.com/articles/101</loc>
 <lastmod>2013-01-02</lastmod>
 <changefreq>weekly</changefreq>
</url>
<url>
 <loc>http://www.yourwebsite.com/articles/102</loc>
 <lastmod>2013-01-02T13:00:12+00:00</lastmod>
 <priority>0.5</priority>
</url>
</urlset>

**Comment by galulex** [comment]
There is no reason for that we have only one page

**Comment by daryakuritsyna** [comment]
Ok, I see
21 авг. 2015 г. 13:28 пользователь "Alex Galushka" notifications@github.com
написал:
