### ISSUE TITLE
URL Canonicalization 

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/browserbadge#31]
http://browserbadge.com/ and http://www.browserbadge.com/ should resolve to the same URL, but currently do not. 

In order to pass this test you must consider using a 301 re-write rule in your .htaccess file so that both addresses (http://example.com and http://www.example.com) resolve to the same URL. 
- If you want to redirect http://www.example.com to http://example.com, you can use this:
  RewriteCond %{HTTP_HOST} ^www.example.com$
  RewriteRule ^/?$ "http:\/\/example.com\/" [R=301,L]
- If you want to redirect http://example.com to http://www.example.com, you can use this:
  RewriteCond %{HTTP_HOST} !^www.example.com$ [NC]
  RewriteRule ^(.*)$ http://www.example.com/$1 [L,R=301]

**Comment by daryakuritsyna** [comment]
Alex, It should be done firstly, because BrowserBadge looses its search position. So, google crawlers spiders determine it as two competitive sites.

**Comment by galulex** [comment]
@daryakuritsyna Done

**Comment by daryakuritsyna** [comment]
Great work!
21 авг. 2015 г. 13:15 пользователь "Alex Galushka" notifications@github.com
написал:
